language: cpp
os: linux
compiler: gcc
sudo: false

script: 
  - cmake .
  - make

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libevent-2.0-5
      - libevent-dev
      - gcc-4.8
      - g++-4.8

notifications:
  email: false