language: cpp
os: linux
compiler: gcc

script: 
  - cmake .
  - make

before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
addons:
  apt:
    packages:
    - libevent-2.0-5
    - libevent-dev
    - gcc-4.8
    - g++-4.8